<a href="https://colab.research.google.com/github/Vignesh141099/NumPy-/blob/main/NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The first thing we want to do is import numpy.

In [1]:
import numpy as np

Let us first define a Python list containing the ages of 6 people.

In [2]:
ages_list = [10, 5, 8, 32, 65, 43]
print(ages_list)

[10, 5, 8, 32, 65, 43]


There are 3 main ways to instantiate a Numpy ndarray object. One of these is to use `np.array(<collection>)`

In [3]:
ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  8 32 65 43]


In [6]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[10  5  8 32 65 43]
Size:	 6
Shape:	 (6,)


In [7]:
zeroArr = np.zeros(5)
print(zeroArr)

[0. 0. 0. 0. 0.]


### Multi-dim

Now let us define a new list containing the weights of these 6 people.

In [8]:
weight_list = [32, 18, 26, 60, 55, 65]

Now, we define an ndarray containing all fo this information, and again print the size and shape of the array.

In [9]:
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10  5  8 32 65 43]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


In [10]:
# 2 X 6 = 1 X 12 = 4 X 3 = 3 X 4 = 12 X 1 

people = people.reshape(12,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10]
 [ 5]
 [ 8]
 [32]
 [65]
 [43]
 [32]
 [18]
 [26]
 [60]
 [55]
 [65]]
Size:	 12
Shape:	 (12, 1)


###### Note: The new shape must be the same "size" as the old shape

## Array Generation

Instead of defining an array manually, we can ask numpy to do it for us.

The `np.arange()` method creates a range of numbers with user defined steps between each.

In [11]:
five_times_table = np.arange(0, 55, 5)
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

The `np.linspace()` method will produce a range of evenly spaced values, starting, ending, and taking as many steps as you specify.

In [15]:
five_spaced = np.linspace(0,50,11)
print(five_spaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


The `.repeat()` method will repeat an object you pas a specified number of times.

In [13]:
twoArr = np.repeat(2, 10)
print(twoArr)

[2 2 2 2 2 2 2 2 2 2]


The `np.eye()` functions will create an identity matrix/array for us.

In [16]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# Operations

There are many, many operations which we can perform on arrays. Below, we demonstrate a few.

What is happening in each line?

In [17]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
print("1:", 2 * five_times_table)
print("2:", 10 + five_times_table)
print("3:", five_times_table - 1)
print("4:", five_times_table/5)
print("5:", five_times_table **2)
print("6:", five_times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


### Speed Test

If we compare the speed at which we can do these operations compared to core python, we will notice a substantial difference.

In [24]:
fives_list = list(range(0,5001,5))
fives_list

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [20]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [25]:
%timeit five_times_table_lge + 5

1.33 µs ± 11.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [22]:
%timeit [e + 5 for e in fives_list]

59.9 µs ± 811 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Boolean string operations can also be performed on nparrays.

In [29]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))
print("e" in words)
["e" in word for word in words]



[False False False False False]
False


[True, True, True, True, False]

# Transpose

In [30]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]] 

[[10 32]
 [ 5 18]
 [ 8 26]
 [32 60]
 [65 55]
 [43 65]]


# Data Types

As previously mentioned, ndarrays can only have one data type. If we want to obtain or change this, we use the `.dtype` attribute.

In [31]:
people.dtype

dtype('int64')

What is the data type of the below ndarray?

In [36]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

ages_with_strings.dtype

dtype('<U21')

What is the dtype of this array?

In [37]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

ages_with_strings.dtype

dtype('int32')

What do you think has happened here?

The list has both integer and string values but while using np.array(list) all the values are denoted as string

In [44]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)


['10' '5' '8' '32' '65' '43']


here we changing the datatype of ages_with_strings as 'int32'

In [38]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[10  5  8 32 65 43]


In [45]:
#to get the size of ages_with_strings use below code

ages_with_strings.size

6

In [46]:
# dividing the ages_with_strings.size by 21

ages_with_strings.size/21

0.2857142857142857

In [48]:
np.array([10, 5, 8, '32', '65', '43']).size

6

The correct way to have changed the data type of the ndarray would have been to use the `.astype()` method, demonstrated below.

In [49]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


### Exercise

* #### Create an array of string numbers, but use dtype to make it an array of floats.
* #### Transpose the matrix, printing the new size and shape.
* #### Use the .astype() method to convert the array to boolean.

## Array Slicing Operations

As before, we can use square brackets and indices to access individual values, and the colon operator to slice the array.

In [50]:
five_times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [51]:
five_times_table[0]

0

In [52]:
five_times_table[-1]

50

In [53]:
five_times_table[:4]

array([ 0,  5, 10, 15])

In [54]:
five_times_table[4:]

array([20, 25, 30, 35, 40, 45, 50])

We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

In [55]:
print(people)
people[:3, :3]

[[10  5  8 32 65 43]
 [32 18 26 60 55 65]]


array([[10,  5,  8],
       [32, 18, 26]])

### Exercise

* Create a numpy array with 50 zeros
* Create a np array of 2 repeated 20 times
* Create a numpy array from 0 to 2 $\pi$ in steps of 0.1

For one of the arrays generated:
* Get the first five values
* Get the last 3 values
* Get the 4th value to the 7th value

We can reverse an array by using `.flip()` or by using the `::` operator.

In [56]:
reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [57]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

[50 45 40 35 30 25 20 15 10  5  0]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

We can also use the `::` operator to select steps of the original array.

In [58]:
five_times_table[0::3] #Every 3rd element starting from 0

array([ 0, 15, 30, 45])

### Exercise
Take one of the arrays you defined and
* #### Reverse it
* #### Only keep every 4th element.
* #### Get every 2nd element, starting from the last and moving backwards.

# Stats

In [ ]:
np.array([1.65432, 5.98765]).round(2)

In [60]:
nums = np.arange(0, 4, 0.2555)

### Exercise

* Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [61]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


## Random

With `np.random`, we can generate a number of types of dataset, and create training data.

The below code simulates a fair coin toss.

In [62]:
flip = np.random.choice([0,1], 10)
flip

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1])

In [63]:
np.random.rand(10,20,9)

array([[[0.99244933, 0.61797465, 0.41323336, ..., 0.6880285 ,
         0.4604185 , 0.30216492],
        [0.2113473 , 0.70842328, 0.63251394, ..., 0.56340431,
         0.27151761, 0.13691359],
        [0.2964996 , 0.78596904, 0.02237397, ..., 0.73342803,
         0.76363133, 0.82171924],
        ...,
        [0.62975411, 0.9263781 , 0.77114471, ..., 0.29202795,
         0.1416982 , 0.59476071],
        [0.95602754, 0.85799835, 0.50707486, ..., 0.90152558,
         0.1951288 , 0.99299216],
        [0.97321514, 0.35224817, 0.38334955, ..., 0.86256082,
         0.39305718, 0.91565697]],

       [[0.89967124, 0.92631695, 0.59010594, ..., 0.43589446,
         0.29439865, 0.58097836],
        [0.4665638 , 0.10556851, 0.01739561, ..., 0.37399234,
         0.8067209 , 0.06168724],
        [0.96028521, 0.54369633, 0.81856663, ..., 0.13439903,
         0.53024081, 0.32057451],
        ...,
        [0.64724086, 0.37694623, 0.71600691, ..., 0.97586348,
         0.76935039, 0.77395875],
        [0.9

We can produce 1000 datapoints of a normally distributed data set by using `np.random.normal()`

In [66]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
s

array([ 1.16259022e-02,  2.23178524e-02, -6.48319565e-02,  2.65170350e-02,
       -1.24560063e-01, -7.55949284e-02, -4.20196212e-03, -1.18729508e-01,
       -1.26957930e-01,  2.95152038e-02, -4.19871244e-02, -2.16846274e-02,
       -6.90897860e-02,  4.72112364e-02,  5.52137344e-02, -5.94842896e-02,
       -1.80964199e-02, -2.08444421e-01, -9.35179551e-02,  7.15399115e-02,
        2.25978970e-01, -4.64010577e-02,  2.89282540e-02,  1.66999393e-02,
        4.80769078e-02, -2.18532052e-02, -5.84030059e-02,  1.14955050e-02,
        3.39191454e-03,  8.66405039e-02,  9.40177233e-02, -1.56377573e-01,
       -6.76847727e-02,  2.56169092e-02,  1.37618223e-01, -2.12799650e-01,
        1.06407789e-01, -1.80269472e-02, -8.68921890e-02,  5.42842100e-02,
       -1.38608856e-01,  3.82765309e-02,  1.49985395e-02, -5.66075262e-02,
       -4.44743195e-02,  1.36461798e-01,  1.12421132e-02,  1.51567247e-01,
        1.19771887e-01,  1.97257535e-02, -1.85124165e-02, -6.34536836e-02,
       -3.96984971e-02,  

### Exercise
* Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
* Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.
