<a href="https://colab.research.google.com/github/Vignesh141099/NumPy-/blob/main/NumPy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Exercise
Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

Generate a matrix (2D numpy array) of the values:


\begin{align}
  \mathbf{A} =
  \begin{pmatrix}
    1 & 2 & 4 \\
    2 & 3 & 0 \\
    0 & 5 & 1
  \end{pmatrix}
\end{align}

Change the dimensions of this array to another permitted shape

In [3]:
import numpy as np

In [8]:
#creating a 1D numpy array

my_list = [7,9,65,33,85,99]
arr_1d=np.array(my_list)
arr_1d

array([ 7,  9, 65, 33, 85, 99])

In [10]:
# Generating a matrix

arr_2d = np.array([[1,2,4],[2,3,0],[0,5,1]])
arr_2d


array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1]])

In [11]:
#Changing the dimensions arr_2d to another permitted shape

arr_reshape = arr_2d.reshape(1,9)
arr_reshape

array([[1, 2, 4, 2, 3, 0, 0, 5, 1]])

In [12]:
arr_reshape = arr_2d.reshape(9,1)
arr_reshape

array([[1],
       [2],
       [4],
       [2],
       [3],
       [0],
       [0],
       [5],
       [1]])

### Exercise

* #### Create an array of string numbers, but use dtype to make it an array of floats.
* #### Transpose the matrix, printing the new size and shape.
* #### Use the .astype() method to convert the array to boolean.

In [20]:
# Create an array of string numbers, but use dtype to make it an array of floats.

item = ['14','12','18','11','21']
arr = np.array(item)
print(arr)
arr.dtype


['14' '12' '18' '11' '21']


dtype('<U2')

In [18]:
# changing the datatype
from numpy.core.memmap import dtype
arr.dtype='float64'
print(arr)
arr.dtype

[1.10343781e-312 0.00000000e+000 1.06099790e-312 1.10343781e-312
 1.18831764e-312 0.00000000e+000 1.03977794e-312 1.20953760e-312
 1.03977794e-312 0.00000000e+000]


dtype('float64')

In [24]:
#Transpose the matrix, printing the new size and shape.
mat = np.array([[1,2,4,5],[2,3,0,6],[0,5,1,7]])
print(mat)
print("shape:\n",mat.shape)
print("size:",mat.size)


[[1 2 4 5]
 [2 3 0 6]
 [0 5 1 7]]
shape:
 (3, 4)
size: 12


In [30]:
# now we are going to transpose the above matrix mat
mat1 = mat.T
print(mat1)
print("shape:\n",mat1.shape)
print("size:",mat1.size)

[[1 2 0]
 [2 3 5]
 [4 0 1]
 [5 6 7]]
shape:
 (4, 3)
size: 12


In [32]:
#Use the .astype() method to convert the array to boolean.
arr = np.array([7,9,65,33,85,99])
print(arr.astype('bool'))

[ True  True  True  True  True  True]


### Exercise

* Create a numpy array with 50 zeros
* Create a np array of 2 repeated 20 times
* Create a numpy array from 0 to 2 $\pi$ in steps of 0.1

For one of the arrays generated:
* Get the first five values
* Get the last 3 values
* Get the 4th value to the 7th value

In [34]:
# to Create a numpy array with 50 zeros

zero=np.zeros(50)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
# To Create a np array of 2 repeated 20 times

repeat= np.repeat(2,20)
repeat

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [38]:
# To Create a numpy array from 0 to 2  π  in steps of 0.1

arr = np.arange(0,2*3.14,0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [40]:
# To Get the first five values
# To Get the last 3 values
# To Get the 4th value to the 7th value - array starts from 0 so 4th value will be 3rd index till 7th value means till 0.6.

a = print(arr[0:5])
b = print(arr[60:])
c = print(arr[3:7])

[0.  0.1 0.2 0.3 0.4]
[6.  6.1 6.2]
[0.3 0.4 0.5 0.6]


### Exercise
Take one of the arrays you defined and
* #### Reverse it
* #### Only keep every 4th element.
* #### Get every 2nd element, starting from the last and moving backwards.

In [42]:
#Reverse it
arr = np.array([7,9,65,33,85,99])
print(arr)
reverse = np.flip(arr)
print(reverse)


[ 7  9 65 33 85 99]
[99 85 33 65  9  7]


In [44]:
#Only keep every 4th element.

arr[0::4]

array([ 7, 85])

In [46]:
#Get every 2nd element, starting from the last and moving backwards.
arr = np.array([7,9,65,33,85,99])
print(arr[::2][::-1])
print (arr[::2][::-1])

[85 65  7]
[85 65  7]


### Exercise

* Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

In [48]:
nums = np.arange(0, 4, 0.2555)
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

In [49]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


### Exercise
* Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
* Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.


In [50]:
#Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws
np.random.choice([1,2,3,4,5,6],10)

array([6, 5, 1, 2, 6, 6, 4, 3, 4, 5])

In [51]:
#Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.
np.random.choice(["H","H","T"],10)

array(['H', 'H', 'T', 'H', 'H', 'T', 'H', 'H', 'T', 'H'], dtype='<U1')